// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicReviewer.Infrastructure.Persistence;

#nullable disable

namespace MusicReviewer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MusicReviewerDbContext))]
    partial class MusicReviewerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.Property<Guid>("ArtistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtistsId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("ArtistGenre");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BeginYear")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Disambiguation")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MusicBrainzId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("SortName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsFeatured")
                        .HasFilter("[IsFeatured] = 1");

                    b.HasIndex("MusicBrainzId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instrument")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverArtUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("FirstReleaseDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("FirstReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MusicBrainzId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("NotabilityScore")
                        .HasColumnType("float");

                    b.Property<int>("PrimaryType")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryTypes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("MusicBrainzId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("ArtistId", "NotabilityScore")
                        .IsDescending(false, true);

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "DiscNumber", "Position");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Ingestion.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedUtc");

                    b.HasIndex("Type", "TargetId");

                    b.ToTable("IngestionJobs");
                });

            modelBuilder.Entity("RecordingGenre", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecordingsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenresId", "RecordingsId");

                    b.HasIndex("RecordingsId");

                    b.ToTable("RecordingGenre");
                });

            modelBuilder.Entity("ArtistGenre", b =>
                {
                    b.HasOne("MusicReviewer.Domain.Catalog.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicReviewer.Domain.Catalog.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Artist", b =>
                {
                    b.OwnsOne("MusicReviewer.Domain.Catalog.WikipediaArticle", "Wikipedia", b1 =>
                        {
                            b1.Property<Guid>("ArtistId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Extract")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("FetchedUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PageTitle")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("PageUrl")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<long>("RevisionId")
                                .HasColumnType("bigint");

                            b1.HasKey("ArtistId");

                            b1.ToTable("Artists");

                            b1.WithOwner()
                                .HasForeignKey("ArtistId");
                        });

                    b.Navigation("Wikipedia");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Credit", b =>
                {
                    b.HasOne("MusicReviewer.Domain.Catalog.Recording", null)
                        .WithMany("Credits")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Recording", b =>
                {
                    b.HasOne("MusicReviewer.Domain.Catalog.Artist", "Artist")
                        .WithMany("Recordings")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MusicReviewer.Domain.Catalog.WikipediaArticle", "Wikipedia", b1 =>
                        {
                            b1.Property<Guid>("RecordingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Extract")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("FetchedUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("PageTitle")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("PageUrl")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<long>("RevisionId")
                                .HasColumnType("bigint");

                            b1.HasKey("RecordingId");

                            b1.ToTable("Recordings");

                            b1.WithOwner()
                                .HasForeignKey("RecordingId");
                        });

                    b.Navigation("Artist");

                    b.Navigation("Wikipedia");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Track", b =>
                {
                    b.HasOne("MusicReviewer.Domain.Catalog.Recording", null)
                        .WithMany("Tracks")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecordingGenre", b =>
                {
                    b.HasOne("MusicReviewer.Domain.Catalog.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicReviewer.Domain.Catalog.Recording", null)
                        .WithMany()
                        .HasForeignKey("RecordingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Artist", b =>
                {
                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("MusicReviewer.Domain.Catalog.Recording", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
