name: Build and deploy MusicReviewer API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore API
        run: dotnet restore src/MusicReviewer.Api/MusicReviewer.Api.csproj

      - name: Publish API
        run: dotnet publish src/MusicReviewer.Api/MusicReviewer.Api.csproj --configuration Release --no-restore --output ./publish

      - name: Deploy API to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MusicReviewer'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_20E33666FA434A4DB69CAF973C122F9F }}